
export const metadata = {
  title: 'new app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-green-400" >{children}</body>
    </html>
  )
}
